# This workflow will build and test a .NET project

name: Build and test

on:
  workflow_call:
    inputs:
      PLATFORM:
        description: 'OS platform/s to run on'
        default: '["ubuntu-latest"]'
        required: false
        type: string
      DOTNET_VERSION:
        description: '.NET-SDK versions to install'
        default: '["8.0.x","9.0.x","10.0.x"]'
        required: false
        type: string

jobs:
  build:

    name: Build and test
    runs-on: ${{ matrix.platform }}

    strategy:
      matrix:
        platform: ${{ fromJson(inputs.PLATFORM) }}

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ join(fromJson(inputs.DOTNET_VERSION), '\n') }}
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: Test
      run: dotnet test --no-build --configuration Release --verbosity normal
